[package]
name = "command_line"
version = "0.1.0"
authors = ["joeyv"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialport = "3.3.0"
bytes = "0.4.12"
byteorder = "1.3.2"